---
output:
  bookdown::pdf_document2:
    keep_tex: false
    number_sections: false
    toc: false
---

```{r setup, echo=FALSE, warning=FALSE, message=FALSE}
knitr::opts_chunk$set(
  echo = FALSE,
  cache = FALSE,
  warning = FALSE,
  fig.align = "center"
)

# Required packages
library(knitr)
library(kableExtra)
library(dplyr)
library(ggplot2)
library(ggpubr)
library(latex2exp)
```

```{r fun-prepare-data}
prepare_data <- function(path) {
  x <- readRDS(path) %>%
    mutate(replicate = as.integer(replicate)) %>%
    arrange(nperm, maxSetSize, nSets, replicate) %>%
    mutate(
      x_pos = (replicate - 2L) * 0.15 + as.numeric(factor(maxSetSize)),
      across(
        .cols = c(nSets, nperm),
        .fns = ~ scales::comma_format()(.x)
      ),
      across(
        .cols = c(nperm, nSets),
        .fns = ~ factor(.x, levels = unique(.x))
      )
    )

  levels(x$nperm) <- latex2exp::TeX(paste0("$\\pi$ = ", levels(x$nperm)))

  return(x)
}
```

```{r fun-plot-time}
plot_time <- function(x, y_breaks, y_max = NULL, expand_upper = 0.05) {
  
  if (is.null(y_max)) {
    y_max <- max(c(y_breaks, x$elapsed_time))
  }
  
  p <- ggplot(x, aes(
    x = x_pos,
    y = elapsed_time,
    color = nSets
  )) +
    geom_point(
      shape = 1,
      size = 1.2,
      stroke = 0.6
    ) +
    facet_wrap(
      ~nperm,
      nrow = 1L,
      labeller = label_parsed
    ) +
    scale_x_continuous(
      breaks = c(1, 2),
      labels = c("500", "1,000"),
      expand = expansion(add = 0.2)
    ) +
    scale_y_continuous(
      breaks = y_breaks,
      limits = c(0, y_max),
      labels = scales::label_comma(),
      expand = expansion(mult = c(5e-3, expand_upper))
    ) +
    scale_color_manual(
      name = "Number of gene sets: ",
      values = structure(palette.colors(n = 3L), names = NULL),
      breaks = c("20,000", "40,000", "60,000")
    ) +
    labs(
      x = "Maximum gene set size",
      y = "Runtime (seconds)"
    ) +
    theme_bw(base_size = 10) +
    theme(
      axis.title.x = element_text(
        color = "black",
        size = 8,
        margin = margin(t = 8, unit = "pt")
      ),
      axis.title.y = element_text(color = "black", size = 8),
      axis.ticks = element_line(
        color = "black",
        linewidth = 0.35
      ),
      axis.text = element_text(color = "black", size = 8),
      panel.border = element_rect(
        linewidth = 0.35,
        fill = NA,
        color = "black"
      ),
      panel.grid.major.x = element_blank(),
      panel.grid.minor.x = element_blank(),
      panel.grid.major.y = element_line(
        color = "grey95",
        linewidth = 0.35
      ),
      panel.grid.minor.y = element_line(
        color = "grey95",
        linewidth = 0.35
      ),
      panel.spacing.x = unit(2, units = "pt"),
      strip.background = element_blank(),
      strip.text = element_text(size = 9),
      plot.margin = unit(c(1, 0, 1, 0), "pt"),
      legend.margin = margin(t = 6, b = 0, unit = "pt"),
      legend.title = element_text(color = "black", size = 8),
      legend.text = element_text(color = "black", size = 8)
    )

  return(p)
}
```

```{r}
height <- 3
width <- 5
```


```{r timing-ssgsea}
# HPGSEA
time_res <- prepare_data("../data/hpgsea_times.rds")

# 10,000 permutations
pa <- filter(time_res, nperm == levels(nperm)[1L]) %>%
  plot_time(y_breaks = seq(0, 1, 0.2), y_max = 1 * 1.05, expand_upper = 0) +
  labs(x = "")

# 100,000 permutations
pb <- filter(time_res, nperm == levels(nperm)[2L]) %>%
  plot_time(y_breaks = seq(0, 2, 0.4), y_max = 2 * 1.05, expand_upper = 0) +
  labs(y = "")

# 1,000,000 permutations
pc <- filter(time_res, nperm == levels(nperm)[3L]) %>%
  plot_time(y_breaks = seq(0, 10, 2), y_max = 10 * 1.05, expand_upper = 0) +
  labs(x = "", y = "")

# Combine plots
p <- ggarrange(
  pa, pb, pc,
  font.label = list(
    face = "bold"
  ),
  nrow = 1L,
  common.legend = TRUE,
  legend = "bottom"
)

ggsave(
  filename = "../figures/figure-1.pdf",
  plot = p, height = height, width = width,
  bg = "white"
)

# For package README
ggsave(
  filename = "../../man/figures/README-figure-1.png",
  plot = p, height = height, width = width,
  bg = "white", dpi = 450
)
```


```{r timing-fgsea}
# FGSEA (single-threaded)
time_res <- prepare_data("../data/fgsea_times_nproc_1.rds")

# 10,000 permutations
pa <- filter(time_res, nperm == levels(nperm)[1L]) %>%
  plot_time(y_breaks = seq(0, 28, 4), y_max = 28 * 1.05, expand_upper = 0) +
  labs(x = "")

# 100,000 permutations
pb <- filter(time_res, nperm == levels(nperm)[2L]) %>%
  plot_time(y_breaks = seq(0, 280, 40), y_max = 280 * 1.05, expand_upper = 0) +
  labs(y = "")

# 1,000,000 permutations
pc <- filter(time_res, nperm == levels(nperm)[3L]) %>%
  plot_time(y_breaks = seq(0, 2800, 400), y_max = 2800 * 1.05, expand_upper = 0) +
  labs(x = "", y = "")

# Combine plots
p <- ggarrange(
  pa, pb, pc,
  font.label = list(
    face = "bold"
  ),
  nrow = 1L,
  common.legend = TRUE,
  legend = "bottom",
  widths = c(32, 34, 36)
)

ggsave(
  filename = "../figures/figure-2.pdf",
  plot = p, height = height, width = width,
  bg = "white"
)

ggsave(
  filename = "../../man/figures/README-figure-2.png",
  plot = p, height = height, width = width,
  bg = "white", dpi = 450
)
```


```{r power}
df <- file.path(
  "..", 
  "data", 
  "power_simulation.rds"
) %>% 
  readRDS()

levels(df$set_size) <- paste0("m = ", levels(df$set_size))
levels(df$method) <- sub("_", ", \u03b1 = ", toupper(levels(df$method)))

p <- ggplot(df, aes(x = prop_DE, y = power, color = method, linetype = mu)) +
  geom_line(
    linewidth = 0.6
  ) +
  facet_wrap(
    ~ set_size,
    nrow = 1L
  ) +
  scale_x_continuous(
    name = "Proportion of DEGs",
    limits = c(0.1, 1),
    breaks = seq(0.2, 1, 0.2),
    expand = expansion(
      mult = 0.05
    )
  ) +
  scale_y_continuous(
    name = "Power",
    limits = c(0, 1),
    breaks = seq(0, 1, 0.2),
    expand = expansion(
      mult = c(5e-3, 0.02)
    )
  ) +
  scale_color_manual(
    name = "Method",
    values = c("black", "grey60", "#ff7f00", "#fdbf6f"),
    breaks = rev(levels(df$method))
  ) +
  scale_linetype_manual(
    name = "Effect size",
    values = c("82", "11", "3132", "solid")
  ) +
  coord_equal() +
  guides(
    color = guide_legend(
      order = 1L,
      nrow = 2L,
      theme = theme(
        legend.key.width = unit(12, "pt")
      )
    ),
    linetype = guide_legend(
      nrow = 2L,
      theme = theme(
        legend.key.width = unit(24, "pt")
      )
    )
  ) +
  theme_bw(
    base_size = 10
  ) +
  theme(
    axis.title.x = element_text(
      color = "black",
      size = 8,
      margin = margin(t = 8, unit = "pt")
    ),
    axis.title.y = element_text(
      color = "black", 
      size = 8
    ),
    axis.ticks = element_line(
      color = "black",
      linewidth = 0.5
    ),
    axis.text = element_text(
      color = "black", 
      size = 8
    ),
    panel.border = element_rect(
      linewidth = 0.5,
      fill = NA,
      color = "black"
    ),
    panel.grid.major.y = element_blank(),
    panel.grid.minor = element_blank(),
    panel.grid.major.x = element_line(
      color = "grey95",
      linewidth = 0.3
    ),
    panel.spacing.x = unit(8, units = "pt"),
    strip.background = element_blank(),
    strip.text = element_text(size = 9),
    plot.margin = unit(c(-6, 1, 1, 1), "pt"),
    legend.key.height = unit(10, "pt"),
    legend.key.spacing.x = unit(12, "pt"),
    legend.margin = margin(t = -6, b = 0, unit = "pt"),
    legend.title = element_text(
      color = "black", 
      size = 8,
      hjust = 0.5
    ),
    legend.text = element_text(
      color = "black", 
      size = 8
    ),
    legend.title.position = "top",
    legend.spacing.x = unit(64, "pt"),
    legend.position = "bottom",
    legend.direction = "horizontal",
    legend.box = "horizontal",
    legend.location = "plot"
  )

ggsave(
  filename = "../figures/power_simulation.pdf",
  plot = p,
  height = 2.7,
  width = 5,
  device = cairo_pdf # correctly render unicode
)
```


```{r table-type-I-error}
df <- file.path(
  "..",
  "data",
  "pvalues_type_I_error.rds"
) %>% 
  readRDS()

kable(
  x = df, 
  col.names = c("Method", sub("^p", "", colnames(df)[-1L])),
  format = "latex",
  digits = 4L
) %>%
  add_header_above(
    header = c(" " = 2L, "Nominal P-value" = 4L)
  )
```


```{r table-inter-gene-cor}
df <- file.path(
  "..",
  "data",
  "pvalues_inter_gene_correlation.rds"
) %>% 
  readRDS()

kable(
  x = df, 
  col.names = c("Method", sub("^p", "", colnames(df)[-1L])),
  format = "latex",
  digits = 4L
) %>%
  add_header_above(
    header = c(" " = 2L, "Nominal P-value" = 4L)
  )
```
