---
output:
  bookdown::pdf_document2:
    keep_tex: false
    number_sections: false
    toc: false
---

```{r setup, echo=FALSE, warning=FALSE, message=FALSE}
knitr::opts_chunk$set(
  echo = FALSE,
  cache = FALSE,
  warning = FALSE,
  fig.align = "center"
)

# Required packages
library(knitr)
library(kableExtra)
library(dplyr)
library(ggplot2)
library(ggpubr)
library(latex2exp)
```

```{r fun-prepare-data}
prepare_data <- function(path) {
  x <- readRDS(path) %>%
    mutate(replicate = as.integer(replicate)) %>%
    arrange(nperm, maxSetSize, nSets, replicate) %>%
    mutate(
      x_pos = (replicate - 2L) * 0.15 + as.numeric(factor(maxSetSize)),
      across(
        .cols = c(nSets, nperm),
        .fns = ~ scales::comma_format()(.x)
      ),
      across(
        .cols = c(nperm, nSets),
        .fns = ~ factor(.x, levels = unique(.x))
      )
    )

  levels(x$nperm) <- latex2exp::TeX(paste0("$\\pi$ = ", levels(x$nperm)))

  return(x)
}
```

```{r fun-plot-time}
plot_time <- function(x, y_breaks, y_max = NULL, expand_upper = 0.05) {
  
  if (is.null(y_max)) {
    y_max <- max(c(y_breaks, x$elapsed_time))
  }
  
  p <- ggplot(x, aes(
    x = x_pos,
    y = elapsed_time,
    color = nSets
  )) +
    geom_point(
      shape = 1,
      size = 1.2,
      stroke = 0.6
    ) +
    facet_wrap(
      ~nperm,
      nrow = 1L,
      labeller = label_parsed
    ) +
    scale_x_continuous(
      breaks = c(1, 2),
      labels = c("500", "1,000"),
      expand = expansion(add = 0.2)
    ) +
    scale_y_continuous(
      breaks = y_breaks,
      limits = c(0, y_max),
      labels = scales::label_comma(),
      expand = expansion(mult = c(5e-3, expand_upper))
    ) +
    scale_color_manual(
      name = "Number of gene sets: ",
      values = structure(palette.colors(n = 3L), names = NULL),
      breaks = c("20,000", "40,000", "60,000")
    ) +
    labs(
      x = "Maximum gene set size",
      y = "Runtime (seconds)"
    ) +
    theme_bw(base_size = 10) +
    theme(
      axis.title.x = element_text(
        color = "black",
        size = 8,
        margin = margin(t = 8, unit = "pt")
      ),
      axis.title.y = element_text(color = "black", size = 8),
      axis.ticks = element_line(
        color = "black",
        linewidth = 0.35
      ),
      axis.text = element_text(color = "black", size = 8),
      panel.border = element_rect(
        linewidth = 0.35,
        fill = NA,
        color = "black"
      ),
      panel.grid.major.x = element_blank(),
      panel.grid.minor.x = element_blank(),
      panel.grid.major.y = element_line(
        color = "grey95",
        linewidth = 0.35
      ),
      panel.grid.minor.y = element_line(
        color = "grey95",
        linewidth = 0.35
      ),
      panel.spacing.x = unit(2, units = "pt"),
      strip.background = element_blank(),
      strip.text = element_text(size = 9),
      plot.margin = unit(c(1, 0, 1, 0), "pt"),
      legend.margin = margin(t = 6, b = 0, unit = "pt"),
      legend.title = element_text(color = "black", size = 8),
      legend.text = element_text(color = "black", size = 8)
    )

  return(p)
}
```

```{r}
height <- 3
width <- 5
```


```{r timing-ssgsea}
# fast-ssGSEA
time_res <- prepare_data("../data/fast-ssGSEA_timing_results.rds")

# 10,000 permutations
pa <- filter(time_res, nperm == levels(nperm)[1L]) %>%
  plot_time(y_breaks = seq(0, 1, 0.2), y_max = 1 * 1.08, expand_upper = 0) +
  labs(x = "")

# 100,000 permutations
pb <- filter(time_res, nperm == levels(nperm)[2L]) %>%
  plot_time(y_breaks = seq(0, 2, 0.4), y_max = 2 * 1.08, expand_upper = 0) +
  labs(y = "")

# 1,000,000 permutations
pc <- filter(time_res, nperm == levels(nperm)[3L]) %>%
  plot_time(y_breaks = seq(0, 12, 2), y_max = 12 * 1.08, expand_upper = 0) +
  labs(x = "", y = "")

# Combine plots
p <- ggarrange(
  pa, pb, pc,
  font.label = list(
    face = "bold"
  ),
  nrow = 1L,
  common.legend = TRUE,
  legend = "bottom"
)

ggsave(
  filename = "../figures/figure-1.pdf",
  plot = p, height = height, width = width,
  bg = "white"
)

# For package README
ggsave(
  filename = "../../man/figures/README-figure-1.png",
  plot = p, height = height, width = width,
  bg = "white", dpi = 450
)
```


```{r timing-fgsea}
# FGSEA (single-threaded)
time_res <- prepare_data("../data/FGSEA_timing_results_nproc_1.rds")

# 10,000 permutations
pa <- filter(time_res, nperm == levels(nperm)[1L]) %>%
  plot_time(y_breaks = seq(0, 30, 4), y_max = 30, expand_upper = 5e-3) +
  labs(x = "")

# 100,000 permutations
pb <- filter(time_res, nperm == levels(nperm)[2L]) %>%
  plot_time(y_breaks = seq(0, 300, 40), y_max = 300, expand_upper = 5e-3) +
  labs(y = "")

# 1,000,000 permutations
pc <- filter(time_res, nperm == levels(nperm)[3L]) %>%
  plot_time(y_breaks = seq(0, 3000, 400), y_max = 3000, expand_upper = 5e-3) +
  labs(x = "", y = "")

# Combine plots
p <- ggarrange(
  pa, pb, pc,
  font.label = list(
    face = "bold"
  ),
  nrow = 1L,
  common.legend = TRUE,
  legend = "bottom",
  widths = c(32, 34, 36)
)

ggsave(
  filename = "../figures/figure-2.pdf",
  plot = p, height = height, width = width,
  bg = "white"
)

ggsave(
  filename = "../../man/figures/README-figure-2.png",
  plot = p, height = height, width = width,
  bg = "white", dpi = 450
)
```
