// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// calc_ES_perm
void calc_ES_perm(SEXP n_same_sign, SEXP n_as_extreme, SEXP sum_ES_perm, const Rcpp::Nullable<Rcpp::IntegerVector> seed, const int nperm, const SEXP ES_dbl, const SEXP ES_end, const SEXP y_dbl, const SEXP r_dbl, const int max_size, const SEXP Rsum_ranks, const SEXP unique_m, const SEXP unique_w);
RcppExport SEXP _hpgsea_calc_ES_perm(SEXP n_same_signSEXP, SEXP n_as_extremeSEXP, SEXP sum_ES_permSEXP, SEXP seedSEXP, SEXP npermSEXP, SEXP ES_dblSEXP, SEXP ES_endSEXP, SEXP y_dblSEXP, SEXP r_dblSEXP, SEXP max_sizeSEXP, SEXP Rsum_ranksSEXP, SEXP unique_mSEXP, SEXP unique_wSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type n_same_sign(n_same_signSEXP);
    Rcpp::traits::input_parameter< SEXP >::type n_as_extreme(n_as_extremeSEXP);
    Rcpp::traits::input_parameter< SEXP >::type sum_ES_perm(sum_ES_permSEXP);
    Rcpp::traits::input_parameter< const Rcpp::Nullable<Rcpp::IntegerVector> >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< const int >::type nperm(npermSEXP);
    Rcpp::traits::input_parameter< const SEXP >::type ES_dbl(ES_dblSEXP);
    Rcpp::traits::input_parameter< const SEXP >::type ES_end(ES_endSEXP);
    Rcpp::traits::input_parameter< const SEXP >::type y_dbl(y_dblSEXP);
    Rcpp::traits::input_parameter< const SEXP >::type r_dbl(r_dblSEXP);
    Rcpp::traits::input_parameter< const int >::type max_size(max_sizeSEXP);
    Rcpp::traits::input_parameter< const SEXP >::type Rsum_ranks(Rsum_ranksSEXP);
    Rcpp::traits::input_parameter< const SEXP >::type unique_m(unique_mSEXP);
    Rcpp::traits::input_parameter< const SEXP >::type unique_w(unique_wSEXP);
    calc_ES_perm(n_same_sign, n_as_extreme, sum_ES_perm, seed, nperm, ES_dbl, ES_end, y_dbl, r_dbl, max_size, Rsum_ranks, unique_m, unique_w);
    return R_NilValue;
END_RCPP
}
// calc_ES_perm_dir
void calc_ES_perm_dir(SEXP n_same_sign, SEXP n_as_extreme, SEXP sum_ES_perm, const Rcpp::Nullable<Rcpp::IntegerVector> seed, const int nperm, const SEXP ES_dbl, const SEXP ES_end, const SEXP y_dbl, const SEXP r_dbl, const int max_size, const SEXP Rsum_ranks, const SEXP unique_m_up, const SEXP unique_w_up, const SEXP unique_m_down, const SEXP unique_w_down, SEXP map_unique_to_pairs_up, SEXP map_unique_to_pairs_down);
RcppExport SEXP _hpgsea_calc_ES_perm_dir(SEXP n_same_signSEXP, SEXP n_as_extremeSEXP, SEXP sum_ES_permSEXP, SEXP seedSEXP, SEXP npermSEXP, SEXP ES_dblSEXP, SEXP ES_endSEXP, SEXP y_dblSEXP, SEXP r_dblSEXP, SEXP max_sizeSEXP, SEXP Rsum_ranksSEXP, SEXP unique_m_upSEXP, SEXP unique_w_upSEXP, SEXP unique_m_downSEXP, SEXP unique_w_downSEXP, SEXP map_unique_to_pairs_upSEXP, SEXP map_unique_to_pairs_downSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type n_same_sign(n_same_signSEXP);
    Rcpp::traits::input_parameter< SEXP >::type n_as_extreme(n_as_extremeSEXP);
    Rcpp::traits::input_parameter< SEXP >::type sum_ES_perm(sum_ES_permSEXP);
    Rcpp::traits::input_parameter< const Rcpp::Nullable<Rcpp::IntegerVector> >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< const int >::type nperm(npermSEXP);
    Rcpp::traits::input_parameter< const SEXP >::type ES_dbl(ES_dblSEXP);
    Rcpp::traits::input_parameter< const SEXP >::type ES_end(ES_endSEXP);
    Rcpp::traits::input_parameter< const SEXP >::type y_dbl(y_dblSEXP);
    Rcpp::traits::input_parameter< const SEXP >::type r_dbl(r_dblSEXP);
    Rcpp::traits::input_parameter< const int >::type max_size(max_sizeSEXP);
    Rcpp::traits::input_parameter< const SEXP >::type Rsum_ranks(Rsum_ranksSEXP);
    Rcpp::traits::input_parameter< const SEXP >::type unique_m_up(unique_m_upSEXP);
    Rcpp::traits::input_parameter< const SEXP >::type unique_w_up(unique_w_upSEXP);
    Rcpp::traits::input_parameter< const SEXP >::type unique_m_down(unique_m_downSEXP);
    Rcpp::traits::input_parameter< const SEXP >::type unique_w_down(unique_w_downSEXP);
    Rcpp::traits::input_parameter< SEXP >::type map_unique_to_pairs_up(map_unique_to_pairs_upSEXP);
    Rcpp::traits::input_parameter< SEXP >::type map_unique_to_pairs_down(map_unique_to_pairs_downSEXP);
    calc_ES_perm_dir(n_same_sign, n_as_extreme, sum_ES_perm, seed, nperm, ES_dbl, ES_end, y_dbl, r_dbl, max_size, Rsum_ranks, unique_m_up, unique_w_up, unique_m_down, unique_w_down, map_unique_to_pairs_up, map_unique_to_pairs_down);
    return R_NilValue;
END_RCPP
}

RcppExport SEXP _C_calc_ES(SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP);
RcppExport SEXP _C_group_sizes(SEXP, SEXP);
RcppExport SEXP _C_pair_szudzik(SEXP, SEXP);
RcppExport SEXP _C_remove_extreme_gene_sets(SEXP, SEXP, SEXP);
RcppExport SEXP _C_rep_int(SEXP, SEXP);

static const R_CallMethodDef CallEntries[] = {
    {"_hpgsea_calc_ES_perm", (DL_FUNC) &_hpgsea_calc_ES_perm, 13},
    {"_hpgsea_calc_ES_perm_dir", (DL_FUNC) &_hpgsea_calc_ES_perm_dir, 17},
    {"_C_calc_ES",                  (DL_FUNC) &_C_calc_ES,                  7},
    {"_C_group_sizes",              (DL_FUNC) &_C_group_sizes,              2},
    {"_C_pair_szudzik",             (DL_FUNC) &_C_pair_szudzik,             2},
    {"_C_remove_extreme_gene_sets", (DL_FUNC) &_C_remove_extreme_gene_sets, 3},
    {"_C_rep_int",                  (DL_FUNC) &_C_rep_int,                  2},
    {NULL, NULL, 0}
};

RcppExport void R_init_hpgsea(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
