// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// calc_ES_perm
void calc_ES_perm(SEXP n_same_sign, SEXP n_as_extreme, SEXP sum_ES_perm, const Rcpp::Nullable<Rcpp::IntegerVector> seed, const int nperm, const SEXP ES, const SEXP ES_end, const SEXP y, const SEXP r, const int max_size, const double sum_ranks, const SEXP L2_m, const SEXP L2_w);
RcppExport SEXP _fast_ssgsea_calc_ES_perm(SEXP n_same_signSEXP, SEXP n_as_extremeSEXP, SEXP sum_ES_permSEXP, SEXP seedSEXP, SEXP npermSEXP, SEXP ESSEXP, SEXP ES_endSEXP, SEXP ySEXP, SEXP rSEXP, SEXP max_sizeSEXP, SEXP sum_ranksSEXP, SEXP L2_mSEXP, SEXP L2_wSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type n_same_sign(n_same_signSEXP);
    Rcpp::traits::input_parameter< SEXP >::type n_as_extreme(n_as_extremeSEXP);
    Rcpp::traits::input_parameter< SEXP >::type sum_ES_perm(sum_ES_permSEXP);
    Rcpp::traits::input_parameter< const Rcpp::Nullable<Rcpp::IntegerVector> >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< const int >::type nperm(npermSEXP);
    Rcpp::traits::input_parameter< const SEXP >::type ES(ESSEXP);
    Rcpp::traits::input_parameter< const SEXP >::type ES_end(ES_endSEXP);
    Rcpp::traits::input_parameter< const SEXP >::type y(ySEXP);
    Rcpp::traits::input_parameter< const SEXP >::type r(rSEXP);
    Rcpp::traits::input_parameter< const int >::type max_size(max_sizeSEXP);
    Rcpp::traits::input_parameter< const double >::type sum_ranks(sum_ranksSEXP);
    Rcpp::traits::input_parameter< const SEXP >::type L2_m(L2_mSEXP);
    Rcpp::traits::input_parameter< const SEXP >::type L2_w(L2_wSEXP);
    calc_ES_perm(n_same_sign, n_as_extreme, sum_ES_perm, seed, nperm, ES, ES_end, y, r, max_size, sum_ranks, L2_m, L2_w);
    return R_NilValue;
END_RCPP
}
// calc_ES_perm_dir
void calc_ES_perm_dir(SEXP n_same_sign, SEXP n_as_extreme, SEXP sum_ES_perm, const Rcpp::Nullable<Rcpp::IntegerVector> seed, const int nperm, const SEXP ES, const SEXP ES_end, const SEXP y, const SEXP r, const int max_size, const double sum_ranks, const SEXP L3_m_up, const SEXP L3_w_up, const SEXP L3_m_down, const SEXP L3_w_down, SEXP map_L3_to_L2_up, SEXP map_L3_to_L2_down);
RcppExport SEXP _fast_ssgsea_calc_ES_perm_dir(SEXP n_same_signSEXP, SEXP n_as_extremeSEXP, SEXP sum_ES_permSEXP, SEXP seedSEXP, SEXP npermSEXP, SEXP ESSEXP, SEXP ES_endSEXP, SEXP ySEXP, SEXP rSEXP, SEXP max_sizeSEXP, SEXP sum_ranksSEXP, SEXP L3_m_upSEXP, SEXP L3_w_upSEXP, SEXP L3_m_downSEXP, SEXP L3_w_downSEXP, SEXP map_L3_to_L2_upSEXP, SEXP map_L3_to_L2_downSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type n_same_sign(n_same_signSEXP);
    Rcpp::traits::input_parameter< SEXP >::type n_as_extreme(n_as_extremeSEXP);
    Rcpp::traits::input_parameter< SEXP >::type sum_ES_perm(sum_ES_permSEXP);
    Rcpp::traits::input_parameter< const Rcpp::Nullable<Rcpp::IntegerVector> >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< const int >::type nperm(npermSEXP);
    Rcpp::traits::input_parameter< const SEXP >::type ES(ESSEXP);
    Rcpp::traits::input_parameter< const SEXP >::type ES_end(ES_endSEXP);
    Rcpp::traits::input_parameter< const SEXP >::type y(ySEXP);
    Rcpp::traits::input_parameter< const SEXP >::type r(rSEXP);
    Rcpp::traits::input_parameter< const int >::type max_size(max_sizeSEXP);
    Rcpp::traits::input_parameter< const double >::type sum_ranks(sum_ranksSEXP);
    Rcpp::traits::input_parameter< const SEXP >::type L3_m_up(L3_m_upSEXP);
    Rcpp::traits::input_parameter< const SEXP >::type L3_w_up(L3_w_upSEXP);
    Rcpp::traits::input_parameter< const SEXP >::type L3_m_down(L3_m_downSEXP);
    Rcpp::traits::input_parameter< const SEXP >::type L3_w_down(L3_w_downSEXP);
    Rcpp::traits::input_parameter< SEXP >::type map_L3_to_L2_up(map_L3_to_L2_upSEXP);
    Rcpp::traits::input_parameter< SEXP >::type map_L3_to_L2_down(map_L3_to_L2_downSEXP);
    calc_ES_perm_dir(n_same_sign, n_as_extreme, sum_ES_perm, seed, nperm, ES, ES_end, y, r, max_size, sum_ranks, L3_m_up, L3_w_up, L3_m_down, L3_w_down, map_L3_to_L2_up, map_L3_to_L2_down);
    return R_NilValue;
END_RCPP
}

RcppExport SEXP _C_calc_ES(SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP);
RcppExport SEXP _C_group_sizes(SEXP, SEXP);
RcppExport SEXP _C_pair_szudzik(SEXP, SEXP);
RcppExport SEXP _C_rep_int(SEXP, SEXP);

static const R_CallMethodDef CallEntries[] = {
    {"_fast_ssgsea_calc_ES_perm", (DL_FUNC) &_fast_ssgsea_calc_ES_perm, 13},
    {"_fast_ssgsea_calc_ES_perm_dir", (DL_FUNC) &_fast_ssgsea_calc_ES_perm_dir, 17},
    {"_C_calc_ES",      (DL_FUNC) &_C_calc_ES,      7},
    {"_C_group_sizes",  (DL_FUNC) &_C_group_sizes,  2},
    {"_C_pair_szudzik", (DL_FUNC) &_C_pair_szudzik, 2},
    {"_C_rep_int",      (DL_FUNC) &_C_rep_int,      2},
    {NULL, NULL, 0}
};

RcppExport void R_init_fast_ssgsea(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
