// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// Rcpp_indexNumericVector
NumericVector Rcpp_indexNumericVector(NumericVector x, IntegerVector idx);
RcppExport SEXP _fast_ssgsea_Rcpp_indexNumericVector(SEXP xSEXP, SEXP idxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type idx(idxSEXP);
    rcpp_result_gen = Rcpp::wrap(Rcpp_indexNumericVector(x, idx));
    return rcpp_result_gen;
END_RCPP
}
// Rcpp_indexIntegerVector
IntegerVector Rcpp_indexIntegerVector(IntegerVector x, IntegerVector idx);
RcppExport SEXP _fast_ssgsea_Rcpp_indexIntegerVector(SEXP xSEXP, SEXP idxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type idx(idxSEXP);
    rcpp_result_gen = Rcpp::wrap(Rcpp_indexIntegerVector(x, idx));
    return rcpp_result_gen;
END_RCPP
}
// Rcpp_matmult_dense
arma::mat Rcpp_matmult_dense(const arma::mat& X, const arma::mat& Y);
RcppExport SEXP _fast_ssgsea_Rcpp_matmult_dense(SEXP XSEXP, SEXP YSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Y(YSEXP);
    rcpp_result_gen = Rcpp::wrap(Rcpp_matmult_dense(X, Y));
    return rcpp_result_gen;
END_RCPP
}
// Rcpp_matmult_sparse
arma::mat Rcpp_matmult_sparse(const arma::mat& X, const arma::sp_mat& Y);
RcppExport SEXP _fast_ssgsea_Rcpp_matmult_sparse(SEXP XSEXP, SEXP YSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::sp_mat& >::type Y(YSEXP);
    rcpp_result_gen = Rcpp::wrap(Rcpp_matmult_sparse(X, Y));
    return rcpp_result_gen;
END_RCPP
}
// Rcpp_calcESCore
arma::mat Rcpp_calcESCore(const double alpha, const int min_size, const arma::mat& Y, const arma::mat& R, const arma::colvec& sumRanks, const arma::sp_mat& A, const arma::mat& M, const arma::mat& W);
RcppExport SEXP _fast_ssgsea_Rcpp_calcESCore(SEXP alphaSEXP, SEXP min_sizeSEXP, SEXP YSEXP, SEXP RSEXP, SEXP sumRanksSEXP, SEXP ASEXP, SEXP MSEXP, SEXP WSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< const int >::type min_size(min_sizeSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type R(RSEXP);
    Rcpp::traits::input_parameter< const arma::colvec& >::type sumRanks(sumRanksSEXP);
    Rcpp::traits::input_parameter< const arma::sp_mat& >::type A(ASEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type M(MSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type W(WSEXP);
    rcpp_result_gen = Rcpp::wrap(Rcpp_calcESCore(alpha, min_size, Y, R, sumRanks, A, M, W));
    return rcpp_result_gen;
END_RCPP
}
// Rcpp_calcESPermCore
arma::mat Rcpp_calcESPermCore(const double alpha, const arma::mat& Y_perm, const arma::mat& R_perm, const double sumRanks_i, const arma::uvec& theta_m_i, const arma::vec& theta_w_i);
RcppExport SEXP _fast_ssgsea_Rcpp_calcESPermCore(SEXP alphaSEXP, SEXP Y_permSEXP, SEXP R_permSEXP, SEXP sumRanks_iSEXP, SEXP theta_m_iSEXP, SEXP theta_w_iSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Y_perm(Y_permSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type R_perm(R_permSEXP);
    Rcpp::traits::input_parameter< const double >::type sumRanks_i(sumRanks_iSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type theta_m_i(theta_m_iSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type theta_w_i(theta_w_iSEXP);
    rcpp_result_gen = Rcpp::wrap(Rcpp_calcESPermCore(alpha, Y_perm, R_perm, sumRanks_i, theta_m_i, theta_w_i));
    return rcpp_result_gen;
END_RCPP
}
// Rcpp_extractPermInfo
List Rcpp_extractPermInfo(const List ES_ls, const NumericMatrix& ES_perm);
RcppExport SEXP _fast_ssgsea_Rcpp_extractPermInfo(SEXP ES_lsSEXP, SEXP ES_permSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const List >::type ES_ls(ES_lsSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type ES_perm(ES_permSEXP);
    rcpp_result_gen = Rcpp::wrap(Rcpp_extractPermInfo(ES_ls, ES_perm));
    return rcpp_result_gen;
END_RCPP
}
// Rcpp_calcAPerm
arma::umat Rcpp_calcAPerm(const arma::uvec& end, const int MAX_SET_SIZE, const bool check);
RcppExport SEXP _fast_ssgsea_Rcpp_calcAPerm(SEXP endSEXP, SEXP MAX_SET_SIZESEXP, SEXP checkSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::uvec& >::type end(endSEXP);
    Rcpp::traits::input_parameter< const int >::type MAX_SET_SIZE(MAX_SET_SIZESEXP);
    Rcpp::traits::input_parameter< const bool >::type check(checkSEXP);
    rcpp_result_gen = Rcpp::wrap(Rcpp_calcAPerm(end, MAX_SET_SIZE, check));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_fast_ssgsea_Rcpp_indexNumericVector", (DL_FUNC) &_fast_ssgsea_Rcpp_indexNumericVector, 2},
    {"_fast_ssgsea_Rcpp_indexIntegerVector", (DL_FUNC) &_fast_ssgsea_Rcpp_indexIntegerVector, 2},
    {"_fast_ssgsea_Rcpp_matmult_dense", (DL_FUNC) &_fast_ssgsea_Rcpp_matmult_dense, 2},
    {"_fast_ssgsea_Rcpp_matmult_sparse", (DL_FUNC) &_fast_ssgsea_Rcpp_matmult_sparse, 2},
    {"_fast_ssgsea_Rcpp_calcESCore", (DL_FUNC) &_fast_ssgsea_Rcpp_calcESCore, 8},
    {"_fast_ssgsea_Rcpp_calcESPermCore", (DL_FUNC) &_fast_ssgsea_Rcpp_calcESPermCore, 6},
    {"_fast_ssgsea_Rcpp_extractPermInfo", (DL_FUNC) &_fast_ssgsea_Rcpp_extractPermInfo, 2},
    {"_fast_ssgsea_Rcpp_calcAPerm", (DL_FUNC) &_fast_ssgsea_Rcpp_calcAPerm, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_fast_ssgsea(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
