# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Dense Matrix Multiplication
#'
#' @description Multiplication of two dense matrices.
#'
#' @param X,Y dense matrices.
#'
#' @returns The product of \code{X} and \code{Y}: a dense matrix.
#'
#' @references Sanderson, C., & Curtin, R. (2016). Armadillo: A template-based
#'   C++ library for linear algebra. The Journal of Open Source Software, 1(2),
#'   26. \url{https://doi.org/10.21105/joss.00026}
#'
#' @noRd
NULL

#' @title Dense-Sparse Matrix Multiplication
#'
#' @description Multiply a dense matrix by a sparse matrix.
#'
#' @param X dense matrix.
#' @param Y sparse matrix.
#'
#' @returns The product of \code{X} and \code{Y}: a dense matrix.
#'
#' @references Sanderson, C., & Curtin, R. (2016). Armadillo: A template-based
#'   C++ library for linear algebra. The Journal of Open Source Software, 1(2),
#'   26. \url{https://doi.org/10.21105/joss.00026}
#'
#' @noRd
NULL

#' @title Core of the .calcES R function
#'
#' @param alpha numeric (\eqn{\geq 0}); the power to which the absolute values
#'   of the entries of \code{X} were raised to construct \code{Y}. If
#'   \code{alpha=0}, computation time may be significantly reduced, though all
#'   genes in each set will contribute equally.
#' @param Y absolute values of the matrix \code{t(X)} raised to the power of
#'   \code{alpha}. Missing values are then imputed with 0.
#' @param R matrix of ranks of the values in each row of \code{X}. Missing
#'   values in \code{X} are assigned a rank of \code{NA}, which are then
#'   imputed with 0.
#' @param sumRanks integer vector; the sums of the ranks in each sample. Equal
#'   to \code{rowSums(R)}.
#' @param A sparse incidence matrix with single genes as rows and gene sets as
#'   columns. A value of 1 indicates that the gene is an element of the set,
#'   while a value of 0 indicates otherwise.
#' @param M matrix with samples as rows and gene sets as columns, where each
#'   entry is the number of genes with nonmissing values in each set.
#' @param W matrix with the same dimensions as \code{M} where each entry is the
#'   number of genes with nonmissing values \emph{not} in each set.
#'
#' @returns A matrix of real-valued enrichment scores with samples as rows and
#'   gene sets as columns. May contain missing values if the corresponding
#'   entry of \code{M} is less than 2.
#'
#' @author Tyler Sagendorf
#'
#' @references Sanderson, C., & Curtin, R. (2016). Armadillo: A template-based
#'   C++ library for linear algebra. The Journal of Open Source Software, 1(2),
#'   26. \url{https://doi.org/10.21105/joss.00026}
#'
#'   Sanderson, C., & Curtin, R. (2019). Practical Sparse Matrices in C++ with
#'   Hybrid Storage and Template-Based Expression Optimisation. Mathematical
#'   and Computational Applications, 24(3), 70. \url{
#'   https://doi.org/10.3390/mca24030070}
#'
#' @noRd
NULL

#' @title Create a Matrix of Random Indices
#'
#' @description Create a matrix where each column is an independent random
#'   sample of indices, taken without replacement from 0 to \code{n_genes - 1}.
#'
#' @param n_genes one more than the maximum index.
#' @param seeds integer vector of random seeds. The length will determine the
#'   number of columns in the output matrix.
#' @param max_set_size the size of the largest gene set. This will determine
#'   the number of rows in the output matrix.
#'
#' @returns A matrix.
#'
#' @seealso
#' https://cran.r-project.org/web/packages/dqrng/vignettes/cpp-api.html
#'
#' @noRd
NULL

#' @title Multiplication of an unseen binary matrix and real-valued matrix
#'
#' @description Compute the product of an unseen binary matrix and real-valued
#'   matrix when the binary matrix is in a specific format. See details.
#'
#' @param set_sizes integer vector of unique set sizes, sorted in ascending
#'   order.
#' @param Y real-valued matrix. The number of rows is equal to
#'   \code{max(set_sizes)}.
#'
#' @details The set_sizes vector acts as a stand-in for the unseen binary
#'   matrix, which has the following characteristics:
#'
#'   1. The first \code{set_sizes[i]} elements of the i-th row are all 1 and
#'   the remaining entries of that row are 0.
#'
#'   2. If the i-th row has n ones, then the i + 1 row will have at least (n +
#'   1) ones.
#'
#'   3. All elements of the last row are 1.
#'
#'   This function has time complexity \code{O(max(set_sizes) * Y.n_cols)}.
#'
#' @author Tyler Sagendorf
#'
#' @references Sanderson, C., & Curtin, R. (2016). Armadillo: A template-based
#'   C++ library for linear algebra. The Journal of Open Source Software, 1(2),
#'   26. \url{https://doi.org/10.21105/joss.00026}
#'
#' @noRd
NULL

#' @title Calculate Permutation Enrichment Scores
#'
#' @param alpha non-negative real value.
#' @param y_i numeric vector of absolute values raised to the power of
#'   \code{alpha}.
#' @param r_i corresponding vector of ranks of the genes in \code{y_i}.
#' @param seeds integer vector of seeds used for random sampling.
#' @param max_set_size integer; the size of the largest gene set that will be
#'   tested. Determines the size of each random sample.
#' @param sumRanks_i numeric; sum of the ranks of all genes.
#' @param theta_m_i integer vector of unique gene set sizes. These will be
#'   unique and sorted in ascending order.
#' @param theta_w_i integer vector of the unique number of genes not in each
#'   set. Equal to the total number of genes with nonmissing values minus the
#'   elements of \code{theta_m_i}.
#'
#' @returns A dense matrix of permutation enrichment scores. Rows correspond to
#'   unique gene set sizes and columns to independent permutations.
#'
#' @details This function has time complexity \code{O(max_set_size *
#'   seeds.size())}.
#'
#' @author Tyler Sagendorf
#'
#' @references Sanderson, C., & Curtin, R. (2016). Armadillo: A template-based
#'   C++ library for linear algebra. The Journal of Open Source Software, 1(2),
#'   26. \url{https://doi.org/10.21105/joss.00026}
#'
#' @noRd
NULL

#' @title Calculate Permutation ES for Directional Gene Sets
#'
#' @inheritParams .Cpp_calcESPerm
#'
#' @param theta_m_i integer vector of the number of up-regulated genes in each
#'   set. Each \code{(theta_m_i, theta_m_d_i)} pair is unique.
#' @param theta_w_i integer vector of the number of genes that are not
#'   up-regulated in the set. Will count genes that are either not in the set
#'   or down-regulated in the set.
#' @param theta_m_d_i integer vector of the number of down-regulated genes in
#'   each set. Each \code{(theta_m_i, theta_m_d_i)} pair is unique.
#' @param theta_w_d_i integer vector of the number of genes that are not
#'   down-regulated in the set. Will count genes that are either not in the set
#'   or up-regulated in the set.
#' @param min_size integer; minimum set size. If the number of "up" or "down"
#'   genes in the set is less than \code{min_size}, the directional ES will be
#'   set to 0.
#'
#' @returns A matrix of permutation ES for directional gene sets.
#'
#' @author Tyler Sagendorf
#'
#' @noRd
NULL

#' @title Find Index of First Positive Value in Sorted Vector
#'
#' @description Given a sorted vector of real-valued numbers, find the index of
#'   the first positive value using a binary search.
#'
#' @param x a sorted real-valued vector.
#'
#' @returns The 0-based index (integer) of the first positive value, or the
#'   size of \code{x} if no positive values were found.
#'
#' @author Tyler Sagendorf
#'
#' @noRd
NULL

#' @title Extract Information About Permutation Enrichment Scores
#'
#' @param x sorted vector of true enrichment scores.
#' @param y vector of permutation enrichment scores (not sorted).
#'
#' @returns A \code{data.table} with 3 columns where the number of rows is
#'   equal to the length of \code{x}.
#'
#' \describe{
#'   \item{"n_same_sign_b"}{integer vector; the number of permutation ES in
#'   \code{y} with the same sign as the corresponding ES in \code{x}.}
#'
#'   \item{"n_as_extreme_b"}{integer vector; the number of permutation ES in
#'   \code{y} that were at least as extreme as the corresponding ES in
#'   \code{x}. At most \code{n_same_sign_b}.}
#'
#'   \item{"sum_ES_perm_b"}{numeric vector; the absolute value of the sum of
#'   the permutation ES in \code{y} that have the same sign as the
#'   corresponding ES in \code{x}.}
#' }
#'
#' @author Tyler Sagendorf
#'
#' @noRd
NULL

#' @title Extract Information from a Permutation Enrichment Score Matrix
#'
#' @description Extract information from a matrix of permutation enrichment
#'   scores run as a single batch.
#'
#' @param ES_ls list of sorted true enrichment scores grouped by gene set size.
#' @param ES_perm matrix of permutation ES. The number of rows is equal to the
#'   length of \code{ES_ls}, while the number of columns is at most the total
#'   number of permutations: more likely, it is a fraction of the total number
#'   of permutations. See the \code{batch_size} parameter of
#'   \code{\link{fast_ssgsea}} for more details.
#'
#' @returns A list of \code{data.table} objects, each with 3 columns:
#'
#' \describe{
#'   \item{"n_same_sign_b"}{integer; the number of permutation ES in each
#'   row of \code{ES_perm} with the same sign as the corresponding ES in
#'   \code{ES}.}
#'   \item{"n_as_extreme_b"}{integer; the number of permutation ES in
#'   each row of \code{ES_perm} that were at least as extreme as the
#'   corresponding ES in \code{ES}. At most \code{"n_same_sign_b"}.}
#'   \item{"sum_ES_perm_b"}{integer; the sum of the absolute values of the
#'   permutation ES that have the same sign as the corresponding ES in
#'   \code{ES}.}
#' }
#'
#' @author Tyler Sagendorf
#'
#' @noRd
NULL

.Cpp_matmult_dense <- function(X, Y) {
    .Call(`_fast_ssgsea_matmult_dense`, X, Y)
}

.Cpp_matmult_sparse <- function(X, Y) {
    .Call(`_fast_ssgsea_matmult_sparse`, X, Y)
}

.Cpp_calcES <- function(alpha, min_size, Y, R, sumRanks, A, M, W) {
    .Call(`_fast_ssgsea_calcES`, alpha, min_size, Y, R, sumRanks, A, M, W)
}

.Cpp_calcESPerm <- function(alpha, y_i, r_i, seeds, max_set_size, sumRanks_i, theta_m_i, theta_w_i) {
    .Call(`_fast_ssgsea_calcESPerm`, alpha, y_i, r_i, seeds, max_set_size, sumRanks_i, theta_m_i, theta_w_i)
}

.Cpp_calcESPerm_dir <- function(alpha, y_i, r_i, seeds, max_set_size, sumRanks_i, theta_m_i, theta_w_i, theta_m_d_i, theta_w_d_i, min_size) {
    .Call(`_fast_ssgsea_calcESPerm_dir`, alpha, y_i, r_i, seeds, max_set_size, sumRanks_i, theta_m_i, theta_w_i, theta_m_d_i, theta_w_d_i, min_size)
}

.Cpp_extractPermInfo <- function(ls, ES_ls, ES_perm) {
    invisible(.Call(`_fast_ssgsea_extractPermInfo`, ls, ES_ls, ES_perm))
}

