# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Get the Index of the First Positive ES for Every Unique Gene Set Size
#'
#' @description Perform binary searches to determine the index of the first
#'   positive ES for each unique gene set size.
#'
#' @param pES_pos_idx pointer to the integer vector that will hold the results.
#' @param n_sizes integer; the number of unique gene set sizes.
#' @param pES pointer to the numeric vector of enrichment scores, sorted in
#'   ascending order by gene set size and then by the values of the ES.
#' @param pES_start pointer to the integer vector with length equal to
#'   \code{n_sizes}. The vector stores the index of the first ES for every
#'   unique gene set size.
#' @param pES_end pointer to the integer vector with length equal to
#'   \code{n_sizes}. Each element is 1 more than the index of the last ES for
#'   every unique gene set size.
#'
#' @returns Nothing. The vector pointed to by \code{pES_pos_idx} is modified in
#'   place. \code{ES_pos_idx} will contain the index of the first positive ES
#'   for every unique gene set size. Each element is greater than or equal to
#'   the corresponding element of \code{ES_start}. If there are no positive ES
#'   for a particular set size, the index will be the corresponding element of
#'   \code{ES_end}.
#'
#' @author Tyler Sagendorf
#'
#' @noRd
NULL

#' @title Update n_same_sign and sum_ES_perm vectors
#'
#' @description Map the vectors with length equal to the number of unique gene
#'   set sizes to the vectors with length equal to the total number of gene
#'   sets.
#'
#' @param pn_same_sign pointer to an integer vector of zeros with length equal
#'   to the number of enrichment scores. Stores the number of permutation ES
#'   with the same sign as each true ES.
#' @param sum_ES_perm pointer to a numeric vector of zeros with length equal to
#'   the number of enrichment scores. Stores the absolute sum of the
#'   permutation ES with the same sign as each true ES.
#' @param n_sizes integer; number of unique gene set sizes.
#' @param nperm integer; total number of permutations.
#' @param pES_start pointer to an integer vector with length equal to
#'   \code{n_sizes}. Stores the index of the first ES for every unique gene set
#'   size.
#' @param pES_end pointer to an integer vector with length equal to
#'   \code{n_sizes}. Each element is 1 more than the index of the last ES for
#'   every unique gene set size.
#' @param pES_pos_idx pointer to an integer vector; the output of
#'   \code{get_ES_pos_idx()}.
#' @param pn_perm_neg pointer to an integer vector; contains the number of
#'   negative permutation ES for every unique gene set size.
#' @param psum_perm_pos pointer to a numeric vector; contains the sum of the
#'   positive permutation ES for every unique gene set size.
#' @param psum_perm_neg pointer to a numeric vector; contains the absolute sum
#'   of the negative permutation ES for every unique gene set size.
#'
#' @returns Nothing. The vectors \code{n_same_sign} and \code{sum_ES_perm} are
#'   modified in place.
#'
#' @author Tyler Sagendorf
#'
#' @noRd
NULL

#' @title Update components for P-values and NES
#'
#' @param pn_as_extreme pointer to an integer vector that stores the number of
#'   permutation ES that are at least as extreme as the ES for each gene set.
#' @param pn_perm_neg pointer to an integer vector that stores the number of
#'   negative permutation ES for each unique gene set size.
#' @param psum_perm_neg pointer to a float vector that stores the absolute sums
#'   of the negative permutation ES.
#' @param psum_perm_pos pointer to a float vector that stores the sums of the
#'   positive permutation ES.
#' @param pES_perm_mat a pointer to a float vector containing permutation ES.
#'   Permutation ES for gene sets of the same size are arranged in blocks of
#'   (at most) 32 consecutive elements.
#' @param pES pointer to a float vector of ES for all gene sets.
#' @param pES_start pointer to an integer vector containing the index of the
#'   first ES for each unique set size.
#' @param pES_pos_idx pointer to an integer vector containing the index of the
#'   first positive ES for each unique set size.
#' @param pES_end pointer to an integer vector containing the 1 more than the
#'   index of the last ES for each unique set size.
#' @param n_sizes integer; the number of unique gene set sizes.
#' @param block_size integer; the size of a block of permutation ES. Between 1
#'   and 32.
#'
#' @details For each unique gene set size, the permutation ES are partitioned
#'   by sign. At the same time, the number of negative permutation ES, as well
#'   as the absolute sums of the negative and positive permutation ES, are
#'   updated. Then, 8 negative ES are compared to a single permutation ES,
#'   iterating over all negative permutation ES before moving to the next 8
#'   negative ES to update n_as_extreme. The process is repeated for the
#'   positive ES and positive permutation ES.
#'
#' @author Tyler Sagendorf
#'
#' @noRd
NULL

#' @title Permutation Tests
#'
#' @description Calculate permutation enrichment scores and update vectors
#'   needed to calculate NES and p-values.
#'
#' @param n_same_sign integer vector of zeros. Used to store the number of
#'   permutation ES with the same sign as each true ES.
#' @param n_as_extreme integer vector of zeros. Used to store the number of
#'   permutation ES that are at least as extreme as each true ES.
#' @param sum_ES_perm numeric vector of zeros. Used to store the absolute sums
#'   of the permutation ES with the same sign as each true ES.
#' @param seed integer or \code{NULL}; seed to obtain reproducible results from
#'   permutation tests.
#' @param nperm integer; total number of permutations.
#' @param ES_dbl numeric vector of enrichment scores, sorted in ascending order
#'   by gene set size and then by the values of the ES.
#' @param ES_end integer vector with length equal to \code{n_sizes}. Each
#'   element is 1 more than the index of the last ES for every unique gene set
#'   size.
#' @param y the absolute values of the gene level statistics raised to some
#'   non-negative power \code{alpha}.
#' @param r the ranks of the gene-level statistics.
#' @param max_size integer; the size of the largest gene set.
#' @param Rsum_ranks the sum of the ranks of all gene-level statistics (sum of
#'   the vector \code{r}).
#' @param unique_m integer vector of unique gene set sizes, sorted in ascending
#'   order.
#' @param unique_w integer vector; the differences between the total number of
#'   genes and the elements of \code{unique_m} (number of genes not in the
#'   set).
#'
#' @returns Nothing. The vectors \code{n_same_sign}, \code{n_as_extreme}, and
#'   \code{sum_ES_perm} are modified in place.
#'
#' @seealso
#' https://cran.r-project.org/web/packages/dqrng/vignettes/cpp-api.html
#'
#' @author Tyler Sagendorf
#'
#' @noRd
NULL

#' @title Permutation Tests for Directional Gene Sets
#'
#' @description Calculate permutation enrichment scores for directional gene
#'   sets and update vectors needed to calculate NES and p-values.
#'
#' @inheritParams calc_ES_perm
#' @param unique_m_up integer vector of the unique number of up-regulated genes
#'   found in the directional gene sets, sorted in ascending order.
#' @param unique_w_up integer vector; the differences between the total number
#'   of genes and the elements of \code{unique_m_up} (unique number of genes
#'   not up-regulated in the set).
#' @param unique_m_down integer vector of the unique number of down-regulated
#'   genes found in the directional gene sets, sorted in ascending order.
#' @param unique_w_down integer vector; the differences between the total
#'   number of genes and the elements of \code{unique_m_down} (unique number of
#'   genes not down-regulated in the set).
#' @param map_unique_to_pairs_up a 1-based integer vector that maps each unique
#'   number of up-regulated genes to the unique pairs of up- and down-regulated
#'   genes.
#' @param map_unique_to_pairs_down a 1-based integer vector that maps each
#'   unique number of down-regulated genes to the unique pairs of up- and
#'   down-regulated genes.
#'
#' @returns Nothing. The vectors \code{n_same_sign}, \code{n_as_extreme}, and
#'   \code{sum_ES_perm} are modified in place.
#'
#' @author Tyler Sagendorf
#'
#' @noRd
NULL

.Cpp_calc_ES_perm <- function(n_same_sign, n_as_extreme, sum_ES_perm, seed, nperm, ES_dbl, ES_end, y_dbl, r_dbl, max_size, Rsum_ranks, unique_m, unique_w) {
    invisible(.Call(`_fast_ssgsea_calc_ES_perm`, n_same_sign, n_as_extreme, sum_ES_perm, seed, nperm, ES_dbl, ES_end, y_dbl, r_dbl, max_size, Rsum_ranks, unique_m, unique_w))
}

.Cpp_calc_ES_perm_dir <- function(n_same_sign, n_as_extreme, sum_ES_perm, seed, nperm, ES_dbl, ES_end, y_dbl, r_dbl, max_size, Rsum_ranks, unique_m_up, unique_w_up, unique_m_down, unique_w_down, map_unique_to_pairs_up, map_unique_to_pairs_down) {
    invisible(.Call(`_fast_ssgsea_calc_ES_perm_dir`, n_same_sign, n_as_extreme, sum_ES_perm, seed, nperm, ES_dbl, ES_end, y_dbl, r_dbl, max_size, Rsum_ranks, unique_m_up, unique_w_up, unique_m_down, unique_w_down, map_unique_to_pairs_up, map_unique_to_pairs_down))
}

