# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Find Index of First Positive Value in Sorted Vector
#'
#' @description Given a sorted vector of real-valued numbers, find the index of
#'   the first positive value using a binary search.
#'
#' @param x a sorted real-valued vector.
#'
#' @returns The 0-based index (integer) of the first positive value, or the
#'   size of \code{x} if no positive values were found.
#'
#' @author Tyler Sagendorf
#'
#' @noRd
NULL

#' @title Fast Vector Indexing
#'
#' @param x a numeric or integer vecctor.
#' @param idx an integer vector of indices of \code{x}. May be longer than
#'   \code{x}.
#'
#' @returns The result of \code{x[idx]}.
#'
#' @note These functions are more than twice as fast as their R counterparts.
#'
#' @noRd
#'
.Rcpp_indexNumericVector <- function(x, idx) {
    .Call(`_fast_ssgsea_Rcpp_indexNumericVector`, x, idx)
}

.Rcpp_indexIntegerVector <- function(x, idx) {
    .Call(`_fast_ssgsea_Rcpp_indexIntegerVector`, x, idx)
}

#' @title Dense Matrix Multiplication
#'
#' @description Multiplication of two dense matrices.
#'
#' @param X,Y dense matrices.
#'
#' @returns The product of \code{X} and \code{Y}: a dense matrix.
#'
#' @references Sanderson, C., & Curtin, R. (2016). Armadillo: A template-based
#'   C++ library for linear algebra. The Journal of Open Source Software, 1(2),
#'   26. \url{https://doi.org/10.21105/joss.00026}
#'
#' @noRd
#'
.Rcpp_matmult_dense <- function(X, Y) {
    .Call(`_fast_ssgsea_Rcpp_matmult_dense`, X, Y)
}

#' @title Dense-Sparse Matrix Multiplication
#'
#' @description Multiply a dense matrix by a sparse matrix.
#'
#' @param X dense matrix.
#' @param Y sparse matrix.
#'
#' @returns The product of \code{X} and \code{Y}: a dense matrix.
#'
#' @references Sanderson, C., & Curtin, R. (2016). Armadillo: A template-based
#'   C++ library for linear algebra. The Journal of Open Source Software, 1(2),
#'   26. \url{https://doi.org/10.21105/joss.00026}
#'
#' @noRd
#'
.Rcpp_matmult_sparse <- function(X, Y) {
    .Call(`_fast_ssgsea_Rcpp_matmult_sparse`, X, Y)
}

#' @title Core of the .calcES R function
#'
#' @param alpha numeric (\eqn{\geq 0}); the power to which the absolute values
#'   of the entries of \code{X} were raised to construct \code{absStat}. If
#'   \code{alpha=0}, computation time may be significantly reduced, though all
#'   genes in each set will contribute equally.
#' @param Y absolute values of the matrix \code{X} raised to the power of
#'   \code{alpha}. Missing values are then imputed with 0.
#' @param R matrix of ranks of the values in each column of \code{X}.
#'   Missing values in \code{X} are assigned a rank of \code{NA}, which are
#'   then imputed with 0.
#' @param sumRanks integer vector; the sums of the ranks in each sample. Equal
#'   to \code{colSums(rankMat)}.
#' @param A sparse incidence matrix with gene sets as rows and genes as
#'   columns. A value of 1 indicates that the gene is an element of the set,
#'   while a value of 0 indicates otherwise.
#' @param M matrix with gene sets as rows and samples as columns, where each
#'   entry is the number of genes with nonmissing values in each set.
#' @param W matrix with the same dimensions as \code{m} where each entry is
#'   the number of genes with nonmissing values \emph{not} in each set.
#'
#' @returns A matrix of real-valued enrichment scores with gene sets as rows
#'   and samples as columns. May contain missing values if the corresponding
#'   entry of \code{m} is less than 2.
#'
#' @author Tyler Sagendorf
#'
#' @references Sanderson, C., & Curtin, R. (2016). Armadillo: A template-based
#'   C++ library for linear algebra. The Journal of Open Source Software, 1(2),
#'   26. \url{https://doi.org/10.21105/joss.00026}
#'
#'   Sanderson, C., & Curtin, R. (2019). Practical Sparse Matrices in C++ with
#'   Hybrid Storage and Template-Based Expression Optimisation. Mathematical
#'   and Computational Applications, 24(3), 70. \url{
#'   https://doi.org/10.3390/mca24030070}
#'
#' @noRd
#'
.Rcpp_calcESCore <- function(alpha, min_size, Y, R, sumRanks, A, M, W) {
    .Call(`_fast_ssgsea_Rcpp_calcESCore`, alpha, min_size, Y, R, sumRanks, A, M, W)
}

#' @title Core of the .calcESPerm R function
#'
#' @param alpha non-negative real value.
#' @param Y_perm matrix of absolute values of the input matrix \code{X} (see
#'   \code{\link{fast_ssgsea}}) raised to the power \code{alpha}. The number of
#'   rows is the size of the largest gene set, while the number of columns is
#'   the number of permutations. Each column is a random sample of values from
#'   the i-th row of matrix \code{Y} (see \code{Rcpp_calcESCore}).
#' @param R_perm matrix with the same dimensions as \code{Y_perm} containing
#'   the corresponding ranks of the values of the genes that were selected for
#'   \code{Y_perm}.
#' @param sumRanks_i integer; sum of the ranks of all genes for sample i.
#' @param A_perm dense incidence matrix where the number of rows is the number
#'   of unique gene set sizes and the number of columns is the size of the
#'   largest gene set. Indicates which genes to use to calculate the
#'   permutation ES.
#' @param theta_m_i integer vector of unique gene set sizes.
#' @param theta_w_i integer vector of unique number of genes not in each set.
#'
#' @returns A dense matrix of permutation enrichment scores. Rows correspond to
#'   unique gene set sizes and columns to independent permutations.
#'
#' @details This function sacrifices some precision by using floats instead of
#'   doubles, but the tradeoff is that the runtime is halved. Using floats does
#'   not appreciably impact the NES or p-values in the final results.
#'
#' @author Tyler Sagendorf
#'
#' @references Sanderson, C., & Curtin, R. (2016). Armadillo: A template-based
#'   C++ library for linear algebra. The Journal of Open Source Software, 1(2),
#'   26. \url{https://doi.org/10.21105/joss.00026}
#'
#' @noRd
#'
.Rcpp_calcESPermCore <- function(alpha, Y_perm, R_perm, sumRanks_i, A_perm, theta_m_i, theta_w_i) {
    .Call(`_fast_ssgsea_Rcpp_calcESPermCore`, alpha, Y_perm, R_perm, sumRanks_i, A_perm, theta_m_i, theta_w_i)
}

#' @title Extract Information About Permutation Enrichment Scores
#'
#' @param x sorted vector of true enrichment scores. Missing values not
#'   allowed.
#' @param y vector of permutation enrichment scores (not necessarily sorted).
#'   All values may be missing.
#'
#' @returns A named list with 3 components, each vectors with length
#'   `length(x)`:
#'
#' \describe{
#'   \item{"n_same_sign_b"}{integer vector; the number of permutation ES in
#'   \code{y} with the same sign as the corresponding ES in \code{x}.}
#'   \item{"n_as_extreme_b"}{integer vector; the number of permutation ES in
#'   \code{y} that were at least as extreme as the corresponding ES in
#'   \code{x}. At most \code{NSameSign.b}.}
#'   \item{"sum_ES_perm_b"}{numeric vector; the absolute value of the sum of
#'   the permutation ES in \code{y} that have the same sign as the
#'   corresponding ES in \code{x}.}
#' }
#'
#' @author Tyler Sagendorf
#'
#' @noRd
#'
.Rcpp_extractPermInfo <- function(x, y) {
    .Call(`_fast_ssgsea_Rcpp_extractPermInfo`, x, y)
}

#' @title Generate a dense incidence matrix for permutation testing
#'
#' @param end positive integer vector; specifies the number of entries in each
#'   row of the result matrix that will be 1.
#' @param MAX_SET_SIZE integer; the size of the largest set. Determines the
#'   number of rows of the matrix.
#' @param check logical; whether to check each value of \code{end} to ensure it
#'   is greater than 0.
#'
#' @returns An binary 0/1 integer matrix. The number of rows is the length of
#'   \code{end}, and the number of columns is \code{MAX_SET_SIZE}.
#'
#' @author Tyler Sagendorf
#'
#' @noRd
#'
.Rcpp_calcAPerm <- function(end, MAX_SET_SIZE, check = FALSE) {
    .Call(`_fast_ssgsea_Rcpp_calcAPerm`, end, MAX_SET_SIZE, check)
}

